WebApplication1/Models/Empleados.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleados
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Empleados()
        {
            this.Citas = new HashSet<Citas>();
            this.ImagenesEmpleados = new HashSet<ImagenesEmpleados>();
            this.Planilla = new HashSet<Planilla>();
        }
    
        public int Id_Empleado { get; set; }
        public string Nombre_Empleado { get; set; }
        public string Apellido_Empleado { get; set; }
        public string Descripcion_Empleado { get; set; }
        public string Correo_Empleado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Citas> Citas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImagenesEmpleados> ImagenesEmpleados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Planilla> Planilla { get; set; }
    }
}

WebApplication1/Models/Planilla.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Planilla
    {
        public int Id_Planilla { get; set; }
        public System.DateTime Fecha_Ingreso { get; set; }
        public decimal Salario { get; set; }
        public string Especializacion { get; set; }
        public int Id_Empleado { get; set; }
    
        public virtual Empleados Empleados { get; set; }
    }
}

WebApplication1/Controllers/EmpleadosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class EmpleadosController : Controller
    {
        private BD_MARYSTYLISEntities db = new BD_MARYSTYLISEntities();

        // GET: Empleados
        [Authorize(Roles = "Administrador")]
        public ActionResult Index()
        {
            return View(db.Empleados.ToList());
        }

        public ActionResult Nosotros()
        {
            return View(db.Empleados.ToList());
        }

        [Authorize(Roles = "Administrador")]
        // GET: Empleados/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Empleados empleados = db.Empleados.Find(id);
            if (empleados == null)
            {
                return HttpNotFound();
            }
            return View(empleados);
        }
        [Authorize(Roles = "Administrador")]
        // GET: Empleados/Create
        public ActionResult Create()
        {
            return View();
        }

        [Authorize(Roles = "Administrador")]
        // POST: Empleados/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id_Empleado,Nombre_Empleado,Apellido_Empleado,Descripcion_Empleado,Correo_Empleado")] Empleados empleados)
        {
            if (ModelState.IsValid)
            {
                db.Empleados.Add(empleados);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(empleados);
        }

        [Authorize(Roles = "Administrador")]
        // GET: Empleados/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Empleados empleados = db.Empleados.Find(id);
            if (empleados == null)
            {
                return HttpNotFound();
            }
            return View(empleados);
        }

        [Authorize(Roles = "Administrador")]
        // POST: Empleados/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id_Empleado,Nombre_Empleado,Apellido_Empleado,Descripcion_Empleado,Correo_Empleado")] Empleados empleados)
        {
            if (ModelState.IsValid)
            {
                db.Entry(empleados).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(empleados);
        }

        [Authorize(Roles = "Administrador")]
        // GET: Empleados/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Empleados empleados = db.Empleados.Find(id);
            if (empleados == null)
            {
                return HttpNotFound();
            }
            return View(empleados);
        }

        // POST: Empleados/Delete/5
        [Authorize(Roles = "Administrador")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Empleados empleados = db.Empleados.Find(id);
            db.Empleados.Remove(empleados);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult EmpleadoImagen(int id)
        {
            Empleados empleados = db.Empleados.Include(p => p.ImagenesEmpleados).FirstOrDefault(p => p.Id_Empleado == id);
            if (empleados == null)
            {
                return HttpNotFound();
            }

            return View(empleados);
        }

        // Acción para mostrar el formulario de creación de una nueva imagen para el producto
        public ActionResult AddImage(int id)
        {
            Empleados empleados = db.Empleados.Find(id);
            if (empleados == null)
            {
                return HttpNotFound();
            }

            return View(new ImagenesEmpleados { Id_Empleado = id });
        }

        // Acción para guardar la nueva imagen en la base de datos
        [HttpPost]
        public ActionResult AddImage(ImagenesEmpleados image, HttpPostedFileBase file)
        {
            if (ModelState.IsValid && file != null && file.ContentLength > 0)
            {
                using (var reader = new BinaryReader(file.InputStream))
                {
                    image.ImageData = reader.ReadBytes(file.ContentLength);
                }

                // Establece la relación entre la imagen y el empleado
                image.Empleados = db.Empleados.Find(image.Id_Empleado);

                db.ImagenesEmpleados.Add(image);
                db.SaveChanges();
                return RedirectToAction("EmpleadoImagen", new { id = image.Id_Empleado });
            }

            return View(image);
        }

        // Acción para mostrar el formulario de edición de una imagen
        public ActionResult EditImage(int id)
        {
            ImagenesEmpleados image = db.ImagenesEmpleados.Find(id);
            if (image == null)
            {
                return HttpNotFound();
            }

            return View(image);
        }

        // Acción para actualizar los datos de una imagen en la base de datos
        [HttpPost]
        public ActionResult EditImage(ImagenesEmpleados image)
        {
            if (ModelState.IsValid)
            {
                db.Entry(image).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("ProductImages", new { id = image.Id_Empleado });
            }

            return View(image);
        }

        // Acción para eliminar una imagen de la base de datos
        public ActionResult DeleteImage(int id)
        {
            ImagenesEmpleados image = db.ImagenesEmpleados.Find(id);
            if (image == null)
            {
                return HttpNotFound();
            }

            return View(image);
        }

        [HttpPost, ActionName("DeleteImage")]
        public ActionResult ConfirmarEliminarImagen(int id)
        {
            ImagenesEmpleados image = db.ImagenesEmpleados.Find(id);
            if (image == null)
            {
                return HttpNotFound();
            }

            db.ImagenesEmpleados.Remove(image);
            db.SaveChanges();
            return RedirectToAction("EmpleadoImagen", new { id = image.Id_Empleado });
        }



        public ActionResult Planilla(int id, string nombre, string apellido)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Empleados empleados = db.Empleados.Find(id);
            PlanillaEmpleados.GeneratePlanillaPDF(id, nombre, apellido);
            if (empleados == null)
            {
                return HttpNotFound();
            }
            return View(empleados);
        }
    }
}

WebApplication1/Controllers/PlanillasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class PlanillasController : Controller
    {
        private BD_MARYSTYLISEntities db = new BD_MARYSTYLISEntities();

        // GET: Planillas
        public ActionResult Index()
        {
            var planilla = db.Planilla.Include(p => p.Empleados);
            return View(planilla.ToList());
        }

        // GET: Planillas/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Planilla planilla = db.Planilla.Find(id);
            if (planilla == null)
            {
                return HttpNotFound();
            }
            return View(planilla);
        }

        // GET: Planillas/Create
        public ActionResult Create()
        {
            ViewBag.Id_Empleado = new SelectList(db.Empleados, "Id_Empleado", "Nombre_Empleado");
            return View();
        }

        // POST: Planillas/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id_Planilla,Fecha_Ingreso,Salario,Especializacion,Id_Empleado")] Planilla planilla)
        {
            if (ModelState.IsValid)
            {
                db.Planilla.Add(planilla);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.Id_Empleado = new SelectList(db.Empleados, "Id_Empleado", "Nombre_Empleado", planilla.Id_Empleado);
            return View(planilla);
        }

        // GET: Planillas/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Planilla planilla = db.Planilla.Find(id);
            if (planilla == null)
            {
                return HttpNotFound();
            }
            ViewBag.Id_Empleado = new SelectList(db.Empleados, "Id_Empleado", "Nombre_Empleado", planilla.Id_Empleado);
            return View(planilla);
        }

        // POST: Planillas/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id_Planilla,Fecha_Ingreso,Salario,Especializacion,Id_Empleado")] Planilla planilla)
        {
            if (ModelState.IsValid)
            {
                db.Entry(planilla).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Id_Empleado = new SelectList(db.Empleados, "Id_Empleado", "Nombre_Empleado", planilla.Id_Empleado);
            return View(planilla);
        }

        // GET: Planillas/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Planilla planilla = db.Planilla.Find(id);
            if (planilla == null)
            {
                return HttpNotFound();
            }
            return View(planilla);
        }

        // POST: Planillas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Planilla planilla = db.Planilla.Find(id);
            db.Planilla.Remove(planilla);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebApplication1/Views/Empleados/AddImage.cshtml
@model WebApplication1.Models.ImagenesEmpleados

@{
    ViewBag.Title = "AddImage";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <div class="card p-4">
        <h2 class="mb-4 text-center">Añadir Imagen</h2>

        @using (Html.BeginForm("AddImage", "Empleados", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            @Html.HiddenFor(model => model.Id_Empleado)

            <div class="form-group row justify-content-center">
                <div class="col-sm-6">
                    @Html.LabelFor(model => model.FileName, "Nombre del archivo", new { @class = "col-form-label" })
                    @Html.TextBoxFor(model => model.FileName, new { @class = "form-control" })
                </div>
            </div>

            <div class="form-group row justify-content-center">
                <div class="col-sm-6 text-center">
                    <label class="col-form-label">Seleccionar Imagen</label>
                    <input type="file" name="file" class="form-control-file" />
                </div>
            </div>

            <div class="form-group text-center">
                <button type="submit" class="btn btn-primary">Añadir Imagen</button>
            </div>
        }
    </div>
</div>

WebApplication1/Views/Empleados/Create.cshtml
@model WebApplication1.Models.Empleados

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container mt-4">
    <h2 class="text-center mb-4">Crear Nuevo Empleado</h2>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-group row">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        </div>

        <div class="form-group row">
            @Html.LabelFor(model => model.Nombre_Empleado, "Nombre", htmlAttributes: new { @class = "col-sm-3 col-form-label" })
            <div class="col-sm-6">
                @Html.EditorFor(model => model.Nombre_Empleado, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre_Empleado, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group row">
            @Html.Label("Empleado", htmlAttributes: new { @class = "col-sm-3 col-form-label" })
            <div class="col-sm-6">
                @Html.EditorFor(model => model.Apellido_Empleado, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Apellido_Empleado, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group row">
            @Html.LabelFor(model => model.Correo_Empleado, "Correo", htmlAttributes: new { @class = "col-sm-3 col-form-label" })
            <div class="col-sm-6">
                @Html.EditorFor(model => model.Correo_Empleado, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Correo_Empleado, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group row">
            @Html.LabelFor(model => model.Descripcion_Empleado, "Descripción", htmlAttributes: new { @class = "col-sm-3 col-form-label" })
            <div class="col-sm-6">
                @Html.EditorFor(model => model.Descripcion_Empleado, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descripcion_Empleado, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group row">
            <div class="col-sm-11 offset-sm-3">
                <input type="submit" value="Crear" class="btn btn-primary mr-2" />
                @Html.ActionLink("Volver a la Lista", "Index", null, new { @class = "btn btn-secondary" })
            </div>
        </div>
    }
</div>

WebApplication1/Views/Empleados/Delete.cshtml
@model WebApplication1.Models.Empleados

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container mt-5">
    <h2>Eliminar</h2>

    <h3>¿Está seguro de eliminar este empleado?</h3>

    <div>
        <hr />
        <dl class="row justify-content-center">
            <dt class="col-4">
                @Html.DisplayNameFor(model => model.Nombre_Empleado)
            </dt>
            <dd class="col-4">
                @Html.DisplayFor(model => model.Nombre_Empleado)
            </dd>

            <dt class="col-4">
                @Html.DisplayNameFor(model => model.Apellido_Empleado)
            </dt>
            <dd class="col-4">
                @Html.DisplayFor(model => model.Apellido_Empleado)
            </dd>

            <dt class="col-4">
                @Html.DisplayNameFor(model => model.Descripcion_Empleado)
            </dt>
            <dd class="col-4">
                @Html.DisplayFor(model => model.Descripcion_Empleado)
            </dd>

            <dt class="col-4">
                @Html.DisplayNameFor(model => model.Correo_Empleado)
            </dt>
            <dd class="col-4">
                @Html.DisplayFor(model => model.Correo_Empleado)
            </dd>
        </dl>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-group">
                <input type="submit" value="Eliminar" class="btn btn-danger" />
                <a href="@Url.Action("Index")" class="btn btn-secondary">Atrás</a>
            </div>
        }
    </div>
</div>

WebApplication1/Views/Empleados/DeleteImage.cshtml
@model WebApplication1.Models.ImagenesEmpleados

@{
    ViewBag.Title = "DeleteImage";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<head>
    <link href="~/Content/Nosotros.css" rel="stylesheet" />
</head>

<section class="titEmp">
    <h1>Eliminar Imagen</h1>
</section>

<h3 class="titConfirmacionEmp">¿Estás seguro de querer eliminar esta imagen?</h3>
<div>
    <dl class="formEmp">
        <dt class="atributosDetallesEmp">
            @Html.DisplayNameFor(model => model.FileName)
        </dt>

        <dd class="atributosEmp">
            @Html.DisplayFor(model => model.FileName)
        </dd>

        <dt class="atributosDetallesEmp">
            @Html.DisplayNameFor(model => model.ImageData)
        </dt>

        <dd class="atributosEmp">
            @Html.DisplayFor(model => model.ImageData)
        </dd>

        <dt class="atributosDetallesEmp">
            @Html.DisplayNameFor(model => model.Empleados.Nombre_Empleado)
        </dt>

        <dd class="atributosEmp">
            @Html.DisplayFor(model => model.Empleados.Nombre_Empleado)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="botones">
            <input type="submit" value="Eliminar" class="btnCrear" /> |
            @Html.ActionLink("Atrás", "Index")
        </div>
    }
</div>

WebApplication1/Views/Empleados/Edit.cshtml
@model WebApplication1.Models.Empleados

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container mt-4">
    <h2 class="text-center mb-4">Editar Empleado</h2>

    @using (Html.BeginForm(null, null, FormMethod.Post, new { @class = "form-horizontal" }))
    {
        @Html.AntiForgeryToken()

        <div class="form-group row">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        </div>

        @Html.HiddenFor(model => model.Id_Empleado)

        <div class="form-group row">
            @Html.LabelFor(model => model.Nombre_Empleado, "Nombre", htmlAttributes: new { @class = "col-sm-3 col-form-label" })
            <div class="col-sm-6">
                @Html.EditorFor(model => model.Nombre_Empleado, new { htmlAttributes = new { @class = "form-control", placeholder = "Nombre" } })
                @Html.ValidationMessageFor(model => model.Nombre_Empleado, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group row">
            @Html.Label("Empleado", htmlAttributes: new { @class = "col-sm-3 col-form-label" })
            <div class="col-sm-6">
                @Html.EditorFor(model => model.Apellido_Empleado, new { htmlAttributes = new { @class = "form-control", placeholder = "Apellido" } })
                @Html.ValidationMessageFor(model => model.Apellido_Empleado, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group row">
            @Html.LabelFor(model => model.Correo_Empleado, "Correo", htmlAttributes: new { @class = "col-sm-3 col-form-label" })
            <div class="col-sm-6">
                @Html.EditorFor(model => model.Correo_Empleado, new { htmlAttributes = new { @class = "form-control", placeholder = "Correo" } })
                @Html.ValidationMessageFor(model => model.Correo_Empleado, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group row">
            @Html.LabelFor(model => model.Descripcion_Empleado, "Descripción", htmlAttributes: new { @class = "col-sm-3 col-form-label" })
            <div class="col-sm-6">
                @Html.EditorFor(model => model.Descripcion_Empleado, new { htmlAttributes = new { @class = "form-control", placeholder = "Descripción" } })
                @Html.ValidationMessageFor(model => model.Descripcion_Empleado, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group row">
            <div class="col-md-offset-5 col-md-6">
                <button type="submit" class="btn btn-primary">Guardar</button>
                @Html.ActionLink("Volver a la Lista", "Index", null, new { @class = "btn btn-secondary ml-2" })
            </div>
        </div>
    }
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebApplication1/Views/Empleados/EmpleadoImagen.cshtml
@using WebApplication1.Models;

@{ ViewBag.Title = "ImagenesEmp";
    Layout = "~/Views/Shared/_Layout.cshtml"; }

@model Empleados

<head>
    <link href="~/Content/Nosotros.css" rel="stylesheet" />
    <style>
        /* Agrega estilos CSS para controlar el tamaño de la imagen */
        .imagenEmpleado {
            max-width: 200px; /* Establece el ancho máximo de la imagen */
            max-height: 150px; /* Establece la altura máxima de la imagen */
        }
    </style>
</head>

<body>

    <section class="titEmp">
        <h1>Imágenes del Empleado</h1>
        <p>Nombre del Empleado: @Model.Nombre_Empleado</p>
    </section>

    <div class="accionesEmp">
        <p class="crearBTN">
            @Html.ActionLink("Añadir Imagen", "AddImage", new { id = Model.Id_Empleado }, new { @class = "btn btn-primary" }) |
            @Html.ActionLink("Atrás", "Index", null, new { @class = "btn btn-secondary" })
        </p>
    </div>

    <table class="table formEmp">
        <thead>
            <tr>
                <th class="text-center">Descripción</th>
                <th class="text-center">Imagen</th>
                <th class="text-center">Acción</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var imagen in Model.ImagenesEmpleados)
            {
                <tr>
                    <td>@imagen.FileName</td>
                    <td>
                        <img src="data:image/png;base64,@Convert.ToBase64String(imagen.ImageData)" alt="Imagen del empleado" class="imagenEmpleado" />
                    </td>
                    <td class="linkEmpleados">
                        @Html.ActionLink("Eliminar", "DeleteImage", new { id = imagen.Id }, new { @class = "btn btn-danger" })
                    </td>
                </tr>
       }
        </tbody>
    </table>

</body>

WebApplication1/Views/Empleados/Index.cshtml
@model IEnumerable<WebApplication1.Models.Empleados>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container mt-4">
    <h2 class="text-center mb-4">Lista de Empleados</h2>

    <div class="row mb-3">
        <div class="col">
            @Html.ActionLink("Crear Nuevo Empleado", "Create", new { @class = "btn btn-primary" })
        </div>
        <div class="col">
            @Html.ActionLink("Agregar Planilla de Empleados", "Index", "Planillas")
        </div>
    </div>
    <br />
    <table class="table table-bordered table-striped">
        <thead class="thead-dark">
            <tr>
                <th class="text-center">Empleado</th>
                <th class="text-center">Descripción</th>
                <th class="text-center">Correo</th>
                <th class="text-center">Acciones</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@Html.DisplayFor(modelItem => item.Nombre_Empleado) @Html.DisplayFor(modelItem => item.Apellido_Empleado)</td>
                    <td>@Html.DisplayFor(modelItem => item.Descripcion_Empleado)</td>
                    <td>@Html.DisplayFor(modelItem => item.Correo_Empleado)</td>
                    <td>
                        <div class="btn-group" role="group">
                            @Html.ActionLink("Editar", "Edit", new { id = item.Id_Empleado }, new { @class = "btn btn-warning btn-sm" })
                            @Html.ActionLink("Eliminar", "Delete", new { id = item.Id_Empleado }, new { @class = "btn btn-danger btn-sm" })
                            @Html.ActionLink("Imagen", "EmpleadoImagen", new { id = item.Id_Empleado }, new { @class = "btn btn-info btn-sm" })
                            @Html.ActionLink("Descargar Planilla", "Planilla", new { id = item.Id_Empleado, nombre = item.Nombre_Empleado, apellido = item.Apellido_Empleado }, new { @class = "btn btn-success btn-sm" })
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

WebApplication1/Views/Empleados/Planilla.cshtml
@{
    ViewBag.Title = "Planilla";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Planilla de empleado en PDF generado correctamente</h2>